import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const promptBuilder = readFileSync(new URL('../src/platform/ai/promptBuilder.js', import.meta.url), 'utf8')
const pipeline = readFileSync(new URL('../src/platform/ai/generationPipeline.js', import.meta.url), 'utf8')
const projectExport = readFileSync(new URL('../src/platform/ai/projectExport.js', import.meta.url), 'utf8')
const controller = readFileSync(new URL('../src/platform/ai/hooks/useAiApplicationController.js', import.meta.url), 'utf8')
const generator = readFileSync(new URL('../src/features/html-app-generator/HtmlAppGenerator.jsx', import.meta.url), 'utf8')
const apiAi = readFileSync(new URL('../api/ai.js', import.meta.url), 'utf8')
const buildPrompt = readFileSync(new URL('../src/ai/buildPrompt.js', import.meta.url), 'utf8')
const viewer = readFileSync(new URL('../src/platform/ai/renderers/HtmlViewer.jsx', import.meta.url), 'utf8')

const block = (name) => promptBuilder.match(new RegExp(`const ${name} = \\[([\\s\\S]*?)\\n\\]`))?.[1] || ''
const createInstructions = block('CREATE_APP_INSTRUCTIONS')
const coCreateInstructions = block('CO_CREATE_APP_INSTRUCTIONS')
const runtimeInstructions = block('RUNTIME_GENERATION_INSTRUCTIONS')

assert.match(createInstructions, /Create mode is simple/)
assert.doesNotMatch(createInstructions, /window\.requestAiGeneration|window\.applyRuntimePayload|runtimePayload instructions|future prompts|precomputed/i)
assert.match(createInstructions, /offline-capable when possible/)
assert.match(promptBuilder, /Un jeu de pendu/)

assert.match(coCreateInstructions, /continuationPlan must exist/)
assert.match(coCreateInstructions, /preload must contain at least one trigger descriptor/)
assert.match(coCreateInstructions, /window\.requestAiGeneration/)
assert.match(coCreateInstructions, /window\.applyRuntimePayload/)
assert.match(coCreateInstructions, /project runtimePayload into user-facing fields/)
assert.match(coCreateInstructions, /quoteField/)
assert.match(coCreateInstructions, /Never render JSON\.stringify\(runtimePayload\)/)
assert.match(coCreateInstructions, /must never define, stub, override, assign, wrap, polyfill, or shadow window\.requestAiGeneration/)
assert.match(coCreateInstructions, /Creatia host injects that bridge/)
assert.match(coCreateInstructions, /await or handle the Promise returned by window\.requestAiGeneration/)
assert.match(coCreateInstructions, /status "unavailable", "blocked", or "timeout"/)
assert.match(coCreateInstructions, /Bridge en attente/)
assert.match(coCreateInstructions, /check window\.CreatiaRuntime\/requestAiGeneration at click time/)
assert.match(coCreateInstructions, /creatia-runtime-ready/)
assert.match(coCreateInstructions, /do not claim the app contacts OpenAI directly/i)
assert.match(coCreateInstructions, /Do not label Co-Create runtime AI as offline-ready/)
assert.doesNotMatch(coCreateInstructions, /offline execution/)
assert.match(coCreateInstructions, /Do not generate future prompts/)
assert.match(coCreateInstructions, /Do not generate future prompts, future content/)

assert.match(runtimeInstructions, /Return \{ "kind": "runtime_generation", "runtimePayload": object/)
assert.match(runtimeInstructions, /page\/screen\/route\/title\/text\/htmlFragment/)
assert.match(runtimeInstructions, /Prefer a statePatch/)
assert.match(promptBuilder, /explicitKind === 'runtime_generation'/)
assert.match(promptBuilder, /runtimePayload: payload\.runtimePayload/)
assert.match(promptBuilder, /traceId: runtimeRequest\.traceId/)

assert.match(controller, /return \{\s*finalStructured,/)
assert.match(controller, /submitRuntimeGeneration/)
assert.match(controller, /runtimeGenerationPendingRef\.current/)
assert.match(controller, /A runtime generation request is already pending/)

assert.match(generator, /runtimeResult\?\.runtimePayload \|\| deriveRuntimePayload/)
assert.match(generator, /state\.page/)
assert.match(generator, /htmlFragment/)
assert.match(generator, /ok: false, responseType: 'generation_error'/)
assert.match(generator, /Runtime generation did not return a usable runtimePayload/)
assert.match(generator, /runtimeDebugEnabled/)
assert.match(generator, /validateRuntimeGenerationResult/)
assert.match(generator, /runtimePayload missing/)
assert.match(generator, /Trace ID courant/)
assert.match(generator, /rawResponses/)
assert.match(generator, /Aucune demande runtime reçue/)
assert.match(generator, /isRuntimeTraceEvent/)
assert.match(generator, /Copier le téléchargement/)
assert.match(generator, /creatia-runtime-host-log/)

assert.match(viewer, /Blocked because: Request already in progress/)
assert.match(viewer, /return \{ status: 'blocked'/)
assert.match(viewer, /window\.applyRuntimePayload\(effectiveRuntimePayload\)/)
assert.match(viewer, /creatia-runtime-ready/)
assert.match(viewer, /runtime\\\\s\*:\\\\s\*\(indisponible\|attendu\|en attente\|non disponible\)/)
assert.match(viewer, /Runtime: connecté/)
assert.match(viewer, /source\.includes\('data-creatia-ui-guard="start-panel"'\)/)
assert.match(viewer, /if \(!guards\) return source/)
assert.match(viewer, /runtimePayload\.page/)
assert.match(viewer, /deliverRuntimeError/)
assert.match(viewer, /payload: effectiveRuntimePayload/)
assert.match(viewer, /runtimePayload: effectiveRuntimePayload/)
assert.match(viewer, /hostStatus: event\.data\.status \|\| 'completed'/)
assert.match(viewer, /Bridge prêt/)
assert.match(viewer, /creatia-runtime-step-log/)
assert.match(viewer, /Runtime: /)
assert.match(viewer, /creatia-runtime-host-log/)
assert.match(viewer, /Runtime generation response timed out\./)
assert.match(viewer, /createTraceId/)
assert.match(viewer, /co-create-/)
assert.match(viewer, /requestAiGeneration_called/)
assert.match(viewer, /generated_requestAiGeneration_stub_replaced/)
assert.match(viewer, /__creatiaHostBridge/)
assert.match(viewer, /host-postmessage-v1/)
assert.match(viewer, /status missing/)
assert.match(viewer, /runtimePayload present but payload absent/)
assert.match(viewer, /runtime_generation present but not transformed to payload/)
assert.match(viewer, /Raw Responses/)

assert.match(promptBuilder, /deriveCoCreateMetadataFromHtml/)
assert.match(pipeline, /runtimePayload\\s\*\\\.\\s\*\(room\|narrative\|choices\|statePatch\|page\|screen\|route\|title\|text\|summary\|items\|htmlFragment\)/)
assert.match(pipeline, /cocreate_does_not_stub_request_ai_generation/)
assert.match(pipeline, /cocreate_runtime_payload_projects_fields/)
assert.match(pipeline, /cocreate_runtime_payload_not_rendered_raw/)
assert.match(pipeline, /rendersRuntimePayloadRaw/)
assert.match(pipeline, /projectsRuntimePayloadFields/)
assert.match(pipeline, /stubsHostRequestAiGeneration/)
assert.match(pipeline, /window\\.requestAiGeneration/)
assert.match(promptBuilder, /Do not label Co-Create runtime AI as offline-ready/)

assert.match(promptBuilder, /extractDeclaredLiteral\(html, 'continuationPlan'\)/)
assert.match(promptBuilder, /extractDeclaredLiteral\(html, 'preload'\)/)
assert.match(projectExport, /deriveRuntimeMetadataFromHtml\(currentApplication\)/)
assert.match(readFileSync(new URL('../src/platform/ai/aiProvider.js', import.meta.url), 'utf8'), /Quota OpenAI insuffisant/)
assert.match(apiAi, /apiTrace/)
assert.match(apiAi, /response_normalized/)
assert.match(apiAi, /runtimePayload missing/)
assert.match(apiAi, /missingFields/)
assert.match(buildPrompt, /buildRuntimeGenerationMessages/)

console.log('Creatia bridge contract tests passed')
